### PR TITLE
fix error with update translations only if `translations` relation populate (#51)

### PR DESCRIPTION
**Pull request by igorveremsky**

### CODE REVIEW

**Comment by igorveremsky** [comment]
think this changes need to merge only after composer update pr https://github.com/OmgDef/yii2-multilingual-behavior/pull/75 will closed

**Comment by OmgDef** [comment]
@igorveremsky this pull request makes duplications of translations. I fixed Travis CI config, but you can run tests on your local machine as well.

**Comment by igorveremsky** [comment]
@OmgDef about ```testUpdateNotPopulatedPost()``` i think this test isn`t correct, you find post with id=2 and want to update some translation fields for it, and to do it you need to usesomething like  ``` ->with('translations')``` that provides additional sql queries and only after that you can update translation fields. i don`t think that this logic is correct. also test name says that translation isnt populated, nut its false because its populated but as ```translation``` key

**Comment by igorveremsky** [comment]
@OmgDef i think this test need to be updated or deleted

**Comment by OmgDef** [comment]
@igorveremsky no, the test is correct. It tests the behavior if a user forgets to load translations. In that case, translations shouldn't be updated. If translations are not loaded, it causes duplications in a translation table. To avoid extra queries you need to rewrite ```saveTranslations``` method and use DAO instead of ActiveRecord, but you won't be able to use behaviors and other benefits of AR for your translations.

**Comment by igorveremsky** [comment]
@OmgDef if you agree i will create PR with https://github.com/igorveremsky/yii2-multilingual-behavior/commit/8c1d920594ac2344170dad095c66103035e06fe2 commit

**Comment by OmgDef** [comment]
@igorveremsky sounds fair. I'll add it by myself. Thanks.

**Pull request merged**
